---
title: "exam4"
output: html_document
date: "2022-11-02"
---
## import libs
```{r}
library(sf)
library(tidyverse)
library(dplyr)
library(janitor)
library(countrycode)
library(here)
```

## read data
```{r}
GE <-
  read_csv(
    here::here(
      "data_exam4",
      "HDR21-22_Composite_indices_complete_time_series.csv"
    ),
    na = " ",
  )

world <- st_read(
  here(
    'data_exam4',
    'World_Countries_(Generalized)',
    'World_Countries__Generalized_.shp'
  )
)
```

## Add country code in GE
```{r}
GE_new <- GE %>%
  clean_names() %>%
  select(iso3, country, gii_2019, gii_2010) %>% # select gender inequality index of 2010 and 2019
  mutate(difference = gii_2019 - gii_2010) %>%
  mutate(iso_code = countrycode(country, origin = 'country.name', destination = 'iso2c')
         #        )%>%
         # mutate(iso_code2=countrycode(iso3, origin ='iso3c', destination = 'iso2c')
  )
```
## join GE(csv) to world(shp)

```{r}
join_GE <- world %>%
  clean_names() %>%
  left_join(.,
            GE_new,
            by = c('iso' = 'iso_code'))

```



